url: http://shimin111.github.io
name: Shi Min
description: I'm a talking slime ball who can write code
timezone: America/Los_Angeles
future: false
lsi: false
permalink: :title
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5
gems: [jekyll-paginate]
